//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelWCFClient.SelServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyData", Namespace="http://schemas.datacontract.org/2004/07/SelWCFServer")]
    [System.SerializableAttribute()]
    public partial class MyData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HighField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsManField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string exInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int High {
            get {
                return this.HighField;
            }
            set {
                if ((this.HighField.Equals(value) != true)) {
                    this.HighField = value;
                    this.RaisePropertyChanged("High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMan {
            get {
                return this.IsManField;
            }
            set {
                if ((this.IsManField.Equals(value) != true)) {
                    this.IsManField = value;
                    this.RaisePropertyChanged("IsMan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string exInfo {
            get {
                return this.exInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.exInfoField, value) != true)) {
                    this.exInfoField = value;
                    this.RaisePropertyChanged("exInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SelServiceReference.ISelService")]
    public interface ISelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelService/SayHello", ReplyAction="http://tempuri.org/ISelService/SayHelloResponse")]
        string SayHello(int vaule);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISelService/SayHello", ReplyAction="http://tempuri.org/ISelService/SayHelloResponse")]
        System.IAsyncResult BeginSayHello(int vaule, System.AsyncCallback callback, object asyncState);
        
        string EndSayHello(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISelService/SayBye")]
        void SayBye(int vaule);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/ISelService/SayBye")]
        System.IAsyncResult BeginSayBye(int vaule, System.AsyncCallback callback, object asyncState);
        
        void EndSayBye(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelService/WhoIs", ReplyAction="http://tempuri.org/ISelService/WhoIsResponse")]
        string WhoIs(SelWCFClient.SelServiceReference.MyData myData);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISelService/WhoIs", ReplyAction="http://tempuri.org/ISelService/WhoIsResponse")]
        System.IAsyncResult BeginWhoIs(SelWCFClient.SelServiceReference.MyData myData, System.AsyncCallback callback, object asyncState);
        
        string EndWhoIs(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISelServiceChannel : SelWCFClient.SelServiceReference.ISelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SayHelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SayHelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WhoIsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public WhoIsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelServiceClient : System.ServiceModel.ClientBase<SelWCFClient.SelServiceReference.ISelService>, SelWCFClient.SelServiceReference.ISelService {
        
        private BeginOperationDelegate onBeginSayHelloDelegate;
        
        private EndOperationDelegate onEndSayHelloDelegate;
        
        private System.Threading.SendOrPostCallback onSayHelloCompletedDelegate;
        
        private BeginOperationDelegate onBeginSayByeDelegate;
        
        private EndOperationDelegate onEndSayByeDelegate;
        
        private System.Threading.SendOrPostCallback onSayByeCompletedDelegate;
        
        private BeginOperationDelegate onBeginWhoIsDelegate;
        
        private EndOperationDelegate onEndWhoIsDelegate;
        
        private System.Threading.SendOrPostCallback onWhoIsCompletedDelegate;
        
        public SelServiceClient() {
        }
        
        public SelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<SayHelloCompletedEventArgs> SayHelloCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SayByeCompleted;
        
        public event System.EventHandler<WhoIsCompletedEventArgs> WhoIsCompleted;
        
        public string SayHello(int vaule) {
            return base.Channel.SayHello(vaule);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSayHello(int vaule, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSayHello(vaule, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndSayHello(System.IAsyncResult result) {
            return base.Channel.EndSayHello(result);
        }
        
        private System.IAsyncResult OnBeginSayHello(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int vaule = ((int)(inValues[0]));
            return this.BeginSayHello(vaule, callback, asyncState);
        }
        
        private object[] OnEndSayHello(System.IAsyncResult result) {
            string retVal = this.EndSayHello(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSayHelloCompleted(object state) {
            if ((this.SayHelloCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SayHelloCompleted(this, new SayHelloCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SayHelloAsync(int vaule) {
            this.SayHelloAsync(vaule, null);
        }
        
        public void SayHelloAsync(int vaule, object userState) {
            if ((this.onBeginSayHelloDelegate == null)) {
                this.onBeginSayHelloDelegate = new BeginOperationDelegate(this.OnBeginSayHello);
            }
            if ((this.onEndSayHelloDelegate == null)) {
                this.onEndSayHelloDelegate = new EndOperationDelegate(this.OnEndSayHello);
            }
            if ((this.onSayHelloCompletedDelegate == null)) {
                this.onSayHelloCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSayHelloCompleted);
            }
            base.InvokeAsync(this.onBeginSayHelloDelegate, new object[] {
                        vaule}, this.onEndSayHelloDelegate, this.onSayHelloCompletedDelegate, userState);
        }
        
        public void SayBye(int vaule) {
            base.Channel.SayBye(vaule);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSayBye(int vaule, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSayBye(vaule, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndSayBye(System.IAsyncResult result) {
            base.Channel.EndSayBye(result);
        }
        
        private System.IAsyncResult OnBeginSayBye(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int vaule = ((int)(inValues[0]));
            return this.BeginSayBye(vaule, callback, asyncState);
        }
        
        private object[] OnEndSayBye(System.IAsyncResult result) {
            this.EndSayBye(result);
            return null;
        }
        
        private void OnSayByeCompleted(object state) {
            if ((this.SayByeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SayByeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SayByeAsync(int vaule) {
            this.SayByeAsync(vaule, null);
        }
        
        public void SayByeAsync(int vaule, object userState) {
            if ((this.onBeginSayByeDelegate == null)) {
                this.onBeginSayByeDelegate = new BeginOperationDelegate(this.OnBeginSayBye);
            }
            if ((this.onEndSayByeDelegate == null)) {
                this.onEndSayByeDelegate = new EndOperationDelegate(this.OnEndSayBye);
            }
            if ((this.onSayByeCompletedDelegate == null)) {
                this.onSayByeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSayByeCompleted);
            }
            base.InvokeAsync(this.onBeginSayByeDelegate, new object[] {
                        vaule}, this.onEndSayByeDelegate, this.onSayByeCompletedDelegate, userState);
        }
        
        public string WhoIs(SelWCFClient.SelServiceReference.MyData myData) {
            return base.Channel.WhoIs(myData);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginWhoIs(SelWCFClient.SelServiceReference.MyData myData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginWhoIs(myData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndWhoIs(System.IAsyncResult result) {
            return base.Channel.EndWhoIs(result);
        }
        
        private System.IAsyncResult OnBeginWhoIs(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SelWCFClient.SelServiceReference.MyData myData = ((SelWCFClient.SelServiceReference.MyData)(inValues[0]));
            return this.BeginWhoIs(myData, callback, asyncState);
        }
        
        private object[] OnEndWhoIs(System.IAsyncResult result) {
            string retVal = this.EndWhoIs(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWhoIsCompleted(object state) {
            if ((this.WhoIsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WhoIsCompleted(this, new WhoIsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WhoIsAsync(SelWCFClient.SelServiceReference.MyData myData) {
            this.WhoIsAsync(myData, null);
        }
        
        public void WhoIsAsync(SelWCFClient.SelServiceReference.MyData myData, object userState) {
            if ((this.onBeginWhoIsDelegate == null)) {
                this.onBeginWhoIsDelegate = new BeginOperationDelegate(this.OnBeginWhoIs);
            }
            if ((this.onEndWhoIsDelegate == null)) {
                this.onEndWhoIsDelegate = new EndOperationDelegate(this.OnEndWhoIs);
            }
            if ((this.onWhoIsCompletedDelegate == null)) {
                this.onWhoIsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWhoIsCompleted);
            }
            base.InvokeAsync(this.onBeginWhoIsDelegate, new object[] {
                        myData}, this.onEndWhoIsDelegate, this.onWhoIsCompletedDelegate, userState);
        }
    }
}
